apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sagsafdsafa
    backstage.io/kubernetes-id: sagsafdsafa
  name: sagsafdsafa
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sagsafdsafa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sagsafdsafa
        backstage.io/kubernetes-id: sagsafdsafa
    spec:
      containers:
      - image: '{{ .Values.config.image.name }}':'{{ .Values.config.image.tag }}'
        imagePullPolicy: IfNotPresent
        name: sagsafdsafa
        resources: {}
        ports:
          - containerPort: 8080 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 5
status: {}
